/* =====================================================
   data.js — Workout definitions with progression levels

   Each exercise has a `levels` array (easiest → hardest).
   `defaultLevel` marks where a beginner-intermediate starts.
   After SESSIONS_TO_LEVEL_UP completions at a level,
   the app suggests moving to the next one.
   ===================================================== */

const WORKOUTS = [
  {
    id: "push",
    name: "יום A — דחיפה",
    emoji: "💪",
    color: "#e74c3c",
    description: "חזה, כתפיים, טריצפס",
    exercises: [
      {
        id: "pushup",
        name: "שכיבות סמיכה",
        defaultLevel: 1,
        rest: 60,
        tips: "גוף ישר כמו קרש, מרפקים 45° מהגוף",
        muscles: "חזה, טריצפס, כתפיים",
        videoSearch: "push up proper form tutorial calisthenics",
        levels: [
          { label: "על ברכיים",        sets: 3, reps: "8"           },
          { label: "רגיל",              sets: 4, reps: "12"          },
          { label: "רגיל — נפח",        sets: 4, reps: "15"          },
          { label: "טמפו 4-2-1",        sets: 3, reps: "10"          },
          { label: "Archer Push-up",    sets: 3, reps: "6 כל צד"    },
          { label: "חד-יד שלילי",       sets: 3, reps: "4 כל צד"    },
        ],
        steps: [
          "הנח ידיים ברוחב כתפיים, אצבעות מופנות קדימה",
          "גוף ישר לחלוטין מהראש עד לעקבים — שמור על זה לאורך כל התרגיל",
          "הורד את הגוף עד שחזה כמעט נוגע ברצפה",
          "מרפקים ב-45° מהגוף — לא פרושים לצדדים",
          "דחוף חזק למעלה עד לנעילת ידיים מלאה",
          "נשום פנימה בירידה, נשום החוצה בדחיפה",
        ],
        commonMistakes: [
          "ישבן גבוה מדי או שוקע למטה",
          "מרפקים פרושים ל-90° — פוגע בכתפיים",
          "טווח תנועה חלקי בלבד",
        ],
      },
      {
        id: "wide-pushup",
        name: "שכיבות סמיכה רחבות",
        defaultLevel: 1,
        rest: 60,
        tips: "ידיים רחבות מהכתפיים — מדגישות את החזה",
        muscles: "חזה חיצוני",
        videoSearch: "wide push up chest workout form",
        levels: [
          { label: "על ברכיים — רחבות", sets: 3, reps: "8"  },
          { label: "רחבות",             sets: 3, reps: "10" },
          { label: "רחבות — נפח",       sets: 4, reps: "15" },
          { label: "טמפו 4-2-1",        sets: 3, reps: "10" },
          { label: "Typewriter",         sets: 3, reps: "6 כל צד" },
        ],
        steps: [
          "הנח ידיים רחוק מהכתפיים — כ-20 ס\"מ מעבר לרוחב הכתף",
          "אצבעות מופנות מעט החוצה",
          "גוף ישר כמו פלאנק לאורך כל התנועה",
          "הורד עד שחזה נוגע ברצפה — טווח מלא",
          "לחץ חזק החוצה ולמעלה בחזרה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "לא מוריד מספיק נמוך",
          "גוף לא ישר — ישבן מורם",
        ],
      },
      {
        id: "pike-pushup",
        name: "Pike Push-ups",
        defaultLevel: 1,
        rest: 75,
        tips: "ירכיים למעלה, ראש לכיוון הרצפה — כמו הכנה ל-Handstand",
        muscles: "כתפיים, טריצפס",
        videoSearch: "pike push up shoulder workout tutorial",
        levels: [
          { label: "ידיים מוגבהות",          sets: 3, reps: "6" },
          { label: "רגיל",                    sets: 3, reps: "8" },
          { label: "רגיל — נפח",              sets: 3, reps: "12" },
          { label: "Decline Pike",            sets: 3, reps: "8" },
          { label: "HSPU שלילי לקיר",         sets: 3, reps: "5" },
        ],
        steps: [
          "התחל בעמדת Push-up רגילה",
          "הרם ירכיים גבוה עד שגוף יוצר צורת V הפוכה",
          "ידיים ברוחב כתפיים, אצבעות קדימה",
          "הורד ראש לכיוון הרצפה בין הידיים",
          "ראש כמעט נוגע ברצפה — עצור",
          "דחוף חזק למעלה, החזר ירכיים לגובה ה-V",
        ],
        commonMistakes: [
          "ירכיים נמוכות מדי — הופך לפוש-אפ רגיל",
          "ראש לא יורד מספיק בין הידיים",
        ],
      },
      {
        id: "dips",
        name: "Dips על כיסא",
        defaultLevel: 1,
        rest: 75,
        tips: "גב צמוד לכיסא, מרפקים אחורה — לא הצידה",
        muscles: "טריצפס, חזה תחתון",
        videoSearch: "tricep dips chair home workout tutorial",
        levels: [
          { label: "ברכיים כפופות",   sets: 3, reps: "8"  },
          { label: "רגליים ישרות",    sets: 3, reps: "10" },
          { label: "רגליים ישרות — נפח", sets: 4, reps: "12" },
          { label: "טמפו 3-1-1",      sets: 3, reps: "8"  },
          { label: "תרמיל על הגב",    sets: 3, reps: "8"  },
        ],
        steps: [
          "שב על קצה כיסא יציב, ידיים אוחזות בקצה הכיסא לצד הירכיים",
          "הזז ישבן קדימה מהכיסא, רגליים ישרות או כפופות",
          "גב קרוב לכיסא לאורך כל התנועה",
          "הורד גוף כלפי מטה — מרפקים כלפי אחורה, לא הצידה",
          "רד עד שמרפקים ב-90° לפחות",
          "דחוף חזק למעלה דרך הידיים לעמדת ההתחלה",
        ],
        commonMistakes: [
          "מרפקים פרושים הצידה — עומס על כתפיים",
          "גוף רחוק מדי מהכיסא",
          "טווח תנועה קטן מדי",
        ],
      },
      {
        id: "diamond-pushup",
        name: "שכיבות יהלום",
        defaultLevel: 1,
        rest: 60,
        tips: "ידיים בצורת יהלום מתחת לחזה",
        muscles: "טריצפס, חזה פנימי",
        videoSearch: "diamond push up triceps tutorial form",
        levels: [
          { label: "על ברכיים",      sets: 3, reps: "6"  },
          { label: "רגיל",            sets: 3, reps: "8"  },
          { label: "רגיל — נפח",     sets: 3, reps: "12" },
          { label: "Close-grip Decline", sets: 3, reps: "10" },
          { label: "יד אחת מסייעת",  sets: 3, reps: "5 כל צד" },
        ],
        steps: [
          "הנח ידיים מתחת לחזה — אגודלות ואצבעות מורות יוצרות צורת יהלום",
          "גוף ישר, ידיים ממורכזות מתחת לגוף",
          "הורד חזה לכיוון הידיים — מרפקים נשארים קרובים לגוף",
          "ודא שחזה כמעט נוגע ביהלום שיצרת",
          "דחוף חזק למעלה עד לנעילה מלאה",
        ],
        commonMistakes: [
          "מרפקים פרושים הצידה",
          "ידיים לא ממורכזות — נטיה לצד אחד",
        ],
      },
    ],
  },

  {
    id: "pull",
    name: "יום B — משיכה",
    emoji: "🏋️",
    color: "#2980b9",
    description: "גב, ביצפס, כתפיים אחוריות",
    exercises: [
      {
        id: "rows",
        name: "Rows מתחת לשולחן",
        defaultLevel: 1,
        rest: 75,
        tips: "שכב מתחת לשולחן יציב, משוך חזה אל הקצה",
        muscles: "גב רחב, ביצפס",
        videoSearch: "australian pull up table row tutorial bodyweight",
        levels: [
          { label: "ברכיים כפופות",    sets: 3, reps: "8"        },
          { label: "רגליים ישרות",     sets: 4, reps: "10"       },
          { label: "רגליים ישרות — נפח", sets: 4, reps: "12"    },
          { label: "רגליים מורמות",   sets: 3, reps: "10"       },
          { label: "Archer Row",       sets: 3, reps: "6 כל צד" },
        ],
        steps: [
          "שכב על הגב מתחת לשולחן יציב — אחוז בקצה השולחן",
          "ידיים ברוחב כתפיים, גוף ישר מהראש לעקבים",
          "רגליים ישרות, עקבים על הרצפה",
          "משוך חזה אל קצה השולחן — שאף פנימה בעלייה",
          "סחט שכמות ביחד בנקודה הגבוהה ביותר",
          "הורד לאט חזרה לעמדת ההתחלה — נשום החוצה",
        ],
        commonMistakes: [
          "ירכיים שוקעות — גוף לא ישר",
          "לא מגיע עם חזה עד השולחן",
          "ירידה מהירה מדי — אל תוותר על הירידה האקסצנטרית",
        ],
      },
      {
        id: "pullup-negative",
        name: "Pull-up שלילי",
        defaultLevel: 1,
        rest: 90,
        tips: "עלה בקפיצה, רד לאט תוך 5 שניות — בונה כוח pull-up",
        muscles: "גב רחב, ביצפס",
        videoSearch: "negative pull up tutorial beginner how to",
        levels: [
          { label: "Negative 3 שניות",  sets: 3, reps: "4" },
          { label: "Negative 5 שניות",  sets: 3, reps: "5" },
          { label: "Negative 7 שניות",  sets: 3, reps: "5" },
          { label: "Pull-up",            sets: 3, reps: "3" },
          { label: "Pull-up — נפח",      sets: 3, reps: "6" },
          { label: "Pull-up — נפח גבוה", sets: 4, reps: "8" },
        ],
        steps: [
          "קפוץ לאחיזה בבר — סנטר מעל הבר, אחיזה רחבה",
          "החזק עצמך בנקודה הגבוהה של ה-Pull-up",
          "הורד את עצמך לאט ובשליטה — ספור 5 שניות",
          "גוף ישר, אל תניף רגליים",
          "כאשר ידיים ישרות לחלוטין — שחרר ונסה שוב",
          "התמקד בהרגשת הגב בכל הירידה",
        ],
        commonMistakes: [
          "ירידה מהירה מדי — אין תועלת מהיר",
          "הנפת גוף ותנופה במקום שליטה",
        ],
      },
      {
        id: "chinup",
        name: "Chin-ups",
        defaultLevel: 1,
        rest: 90,
        tips: "אחיזה כפות מופנות אליך — קל יותר מ-pull-up",
        muscles: "ביצפס, גב",
        videoSearch: "chin up tutorial proper form beginners",
        levels: [
          { label: "קפיצה + Negative",  sets: 3, reps: "4"  },
          { label: "מקסימום",            sets: 3, reps: "max" },
          { label: "3×5",                sets: 3, reps: "5"  },
          { label: "3×8",                sets: 3, reps: "8"  },
          { label: "4×10",               sets: 4, reps: "10" },
          { label: "L-sit Chin-up",      sets: 3, reps: "5"  },
        ],
        steps: [
          "אחוז בבר כאשר כפות הידיים מופנות אליך — ידיים ברוחב כתפיים",
          "תלה עם ידיים ישרות לחלוטין — שכמות קצת לאחור",
          "משוך עצמך למעלה — מרפקים לצד הגוף ולמטה",
          "עלה עד שסנטר מעל הבר",
          "הורד לאט ובשליטה עד לתלייה מלאה",
          "אל תניף — תנועה נקייה ואיטית",
        ],
        commonMistakes: [
          "לא מגיע לתלייה מלאה בתחתית",
          "הנפת גוף לצבור תנופה",
          "מרפקים פרושים הצידה",
        ],
      },
      {
        id: "superman",
        name: "Superman Hold",
        defaultLevel: 1,
        rest: 45,
        tips: "שכב על הבטן, הרם ידיים ורגליים בו זמנית",
        muscles: "גב תחתון, ישבן",
        videoSearch: "superman hold back extension tutorial",
        levels: [
          { label: "15 שניות",            sets: 3, reps: "15 שניות" },
          { label: "20 שניות",            sets: 3, reps: "20 שניות" },
          { label: "30 שניות",            sets: 3, reps: "30 שניות" },
          { label: "חלופת ידיים-רגליים",  sets: 3, reps: "20 שניות" },
        ],
        steps: [
          "שכב על הבטן, ידיים מושטות קדימה, רגליים ישרות",
          "הרם ידיים, חזה ורגליים בו-זמנית מהרצפה",
          "סחט ישבן וגב תחתון בנקודה הגבוהה",
          "ראש בקו ישר עם עמוד השדרה — אל תרים ראש גבוה",
          "החזק את העמדה לאורך הזמן הנדרש",
          "הורד בשליטה לרצפה",
        ],
        commonMistakes: [
          "הרמת ראש גבוה — לחץ על צוואר",
          "הרמת רק ידיים או רק רגליים",
        ],
      },
      {
        id: "face-pull",
        name: "Face Pull עם גומייה",
        defaultLevel: 1,
        rest: 45,
        tips: "קשור גומייה בגובה הפנים, משוך אל הפנים",
        muscles: "כתפיים אחוריות, גב עליון",
        videoSearch: "face pull resistance band tutorial rotator cuff",
        levels: [
          { label: "גומייה קלה",        sets: 3, reps: "10" },
          { label: "רגיל",              sets: 3, reps: "12" },
          { label: "נפח",               sets: 3, reps: "15" },
          { label: "גומייה + Rotation", sets: 3, reps: "12" },
        ],
        steps: [
          "קשור גומייה לגובה הפנים — לדלת, עמוד או בר",
          "אחוז בשני קצות הגומייה, ידיים בגובה הפנים",
          "עמוד רחוק מספיק שהגומייה מתוחה",
          "משוך את הגומייה ישירות לכיוון הפנים — מרפקים גבוהים",
          "בנקודה הסופית — מרפקים מאחורי הראש, אגרופים ליד האוזניים",
          "הורד לאט בשליטה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "מרפקים נופלים למטה במהלך המשיכה",
          "תנועה מהירה מדי ללא שליטה",
        ],
      },
    ],
  },

  {
    id: "legs-core",
    name: "יום C — רגליים + ליבה",
    emoji: "🦵",
    color: "#27ae60",
    description: "רגליים, ישבן, בטן",
    exercises: [
      {
        id: "squat",
        name: "סקוואט",
        defaultLevel: 1,
        rest: 60,
        tips: "ברכיים מעל אצבעות הרגל, גב ישר, ירד עד 90°",
        muscles: "ארבע ראשי, ישבן",
        videoSearch: "bodyweight squat proper form tutorial",
        levels: [
          { label: "Box Squat",          sets: 3, reps: "12"        },
          { label: "רגיל",               sets: 4, reps: "15"        },
          { label: "נפח",                sets: 4, reps: "20"        },
          { label: "Jump Squat",         sets: 3, reps: "12"        },
          { label: "Pistol — שלילי",     sets: 3, reps: "5 כל רגל" },
          { label: "Pistol Squat",       sets: 3, reps: "5 כל רגל" },
        ],
        steps: [
          "עמוד ברוחב כתפיים, אצבעות הרגל מופנות מעט החוצה",
          "ידיים ישרות קדימה לאיזון, או מקופלות על החזה",
          "שמור גב ישר ולחץ חזה החוצה לאורך כל התנועה",
          "הורד עצמך כאילו אתה יושב על כיסא — ישבן לאחור ולמטה",
          "ירד עד שירכיים מקבילות לרצפה (90°) לפחות",
          "ברכיים נשארות מעל אצבעות הרגל — לא נכנסות פנימה",
          "דחוף דרך העקבים לחזרה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "ברכיים נכנסות פנימה — פוגע בברכיים",
          "עקבים מתרוממים מהרצפה",
          "גב מתעגל — לחץ חזה קדימה",
        ],
      },
      {
        id: "lunge",
        name: "לאנג'ים לאחור",
        defaultLevel: 1,
        rest: 60,
        tips: "צעד גדול לאחור, ברך אחורית כמעט נוגעת ברצפה",
        muscles: "ארבע ראשי, ישבן, ירכיים",
        videoSearch: "reverse lunge proper form tutorial bodyweight",
        levels: [
          { label: "Static Lunge",        sets: 3, reps: "8 כל רגל"  },
          { label: "Reverse Lunge",       sets: 3, reps: "10 כל רגל" },
          { label: "Reverse Lunge — נפח", sets: 3, reps: "15 כל רגל" },
          { label: "Bulgarian Split",     sets: 3, reps: "8 כל רגל"  },
          { label: "Bulgarian — נפח",     sets: 3, reps: "12 כל רגל" },
        ],
        steps: [
          "עמוד זקוף עם ידיים על הירכיים",
          "צעד צעד גדול לאחור עם רגל אחת",
          "הורד ברך אחורית לכיוון הרצפה — כמעט נוגעת",
          "ברך קדמית מעל עקב — לא חורגת מעבר לאצבע הרגל",
          "גב ישר לאורך כל התנועה",
          "דחוף דרך הרגל הקדמית לחזרה לעמדה",
        ],
        commonMistakes: [
          "ברך קדמית חורגת מעבר לאצבע הרגל",
          "פלג גוף עליון נוטה קדימה",
          "צעד קצר מדי — ברך לא יורדת מספיק",
        ],
      },
      {
        id: "glute-bridge",
        name: "Glute Bridge",
        defaultLevel: 1,
        rest: 45,
        tips: "שכב, כפות רגליים קרוב לישבן, הרם ורד לאט",
        muscles: "ישבן, ירכיים אחוריות",
        videoSearch: "glute bridge tutorial proper form hip thrust",
        levels: [
          { label: "שתי רגליים",          sets: 3, reps: "12"        },
          { label: "שתי רגליים — נפח",    sets: 3, reps: "15"        },
          { label: "נפח גבוה",             sets: 3, reps: "20"        },
          { label: "Single Leg",           sets: 3, reps: "10 כל רגל" },
          { label: "Elevated Single Leg",  sets: 3, reps: "10 כל רגל" },
        ],
        steps: [
          "שכב על הגב, ברכיים כפופות, כפות רגליים שטוחות על הרצפה",
          "כפות הרגל קרוב לישבן — כ-30 ס\"מ",
          "ידיים לצד הגוף, כפות ידיים מטה",
          "דחוף דרך העקבים — הרם ישבן למעלה",
          "בנקודה הגבוהה: גוף ישר מכתפיים לברכיים, סחט ישבן חזק",
          "החזק שניה, ואז הורד לאט לרצפה",
        ],
        commonMistakes: [
          "לא סוחט ישבן בחלק העליון",
          "עקבים מתרוממים מהרצפה",
          "ירד מהר מדי — לנצל את הירידה האקסצנטרית",
        ],
      },
      {
        id: "plank",
        name: "פלאנק",
        defaultLevel: 1,
        rest: 45,
        tips: "גוף ישר, ישבן לא למעלה ולא למטה, נשום!",
        muscles: "ליבה, כתפיים",
        videoSearch: "plank proper form tutorial core workout",
        levels: [
          { label: "20 שניות",           sets: 3, reps: "20 שניות" },
          { label: "40 שניות",           sets: 3, reps: "40 שניות" },
          { label: "60 שניות",           sets: 3, reps: "60 שניות" },
          { label: "Side Plank",         sets: 3, reps: "30s כל צד" },
          { label: "Plank + Shoulder Tap", sets: 3, reps: "20 טפיחות" },
        ],
        steps: [
          "שכב על הבטן, עלה למרפקים — מרפקים ישר מתחת לכתפיים",
          "גוף ישר מהראש לעקבים — דמיין קרש",
          "ישבן לא גבוה ולא נמוך — בדיוק בקו הגוף",
          "לחץ אגרופים לרצפה ולחץ ישבן קלות",
          "ראש בקו ישר עם עמוד השדרה — אל תרים ואל תרכין",
          "נשום נורמלית לאורך כל ההחזקה",
        ],
        commonMistakes: [
          "ישבן גבוה מדי — הופך לפוזיציית V",
          "ישבן שוקע למטה — לחץ על גב תחתון",
          "לעצור נשימה — גורם לסחרחורת",
        ],
      },
      {
        id: "mountain-climber",
        name: "Mountain Climbers",
        defaultLevel: 1,
        rest: 45,
        tips: "קצב מהיר, גוף ישר כמו פלאנק",
        muscles: "ליבה, לב-ריאה",
        videoSearch: "mountain climbers proper form cardio core tutorial",
        levels: [
          { label: "איטי",              sets: 3, reps: "10 כל רגל" },
          { label: "רגיל",              sets: 3, reps: "20 כל רגל" },
          { label: "נפח",               sets: 3, reps: "30 כל רגל" },
          { label: "Cross-body",        sets: 3, reps: "20 כל רגל" },
        ],
        steps: [
          "התחל בעמדת Push-up מורחבת — ידיים ישר מתחת לכתפיים",
          "גוף ישר כמו פלאנק — שמור על זה לכל האימון",
          "משוך ברך ימין לכיוון החזה",
          "בזריזות החלף — שלח ימין אחורה ומשוך שמאל קדימה",
          "המשך בקצב מהיר — כמו ריצה במקום",
          "נשום קצבית ואל תעצור נשימה",
        ],
        commonMistakes: [
          "ישבן מורם למעלה — שובר את קו הגוף",
          "ידיים לא ישר מתחת לכתפיים",
          "תנועה איטית מדי — מאבד אפקט קרדיו",
        ],
      },
      {
        id: "hollow-body",
        name: "Hollow Body Hold",
        defaultLevel: 1,
        rest: 45,
        tips: "גב שטוח לרצפה, ידיים ורגליים מורמים, גב תחתון לוחץ לרצפה",
        muscles: "ליבה עמוקה",
        videoSearch: "hollow body hold tutorial gymnastics core",
        levels: [
          { label: "ברכיים כפופות",    sets: 3, reps: "15 שניות" },
          { label: "רגיל",              sets: 3, reps: "20 שניות" },
          { label: "נפח",               sets: 3, reps: "35 שניות" },
          { label: "Hollow Body Rocks", sets: 3, reps: "15"        },
        ],
        steps: [
          "שכב על הגב עם ידיים לצד הגוף",
          "הדחק גב תחתון לרצפה — זה הכי חשוב!",
          "הרם כתפיים ורגליים מהרצפה בו-זמנית",
          "ידיים מושטות מאחורי הראש, רגליים ישרות",
          "גב תחתון תמיד בלחיצה לרצפה — לא ירים",
          "לגרסה קלה יותר: כופף ברכיים לזווית 90°",
          "החזק את העמדה — נשום!",
        ],
        commonMistakes: [
          "גב תחתון מתרומם מהרצפה — מאבד הפעלת ליבה",
          "לא שומר מתח גוף — גוף שקוע",
        ],
      },
    ],
  },
];
