/* =====================================================
   data.js — Workout definitions with progression levels

   Each exercise has a `levels` array (easiest → hardest).
   `defaultLevel` marks where a beginner-intermediate starts.
   After SESSIONS_TO_LEVEL_UP completions at a level,
   the app suggests moving to the next one.
   ===================================================== */

const WORKOUTS = [
  {
    id: "push",
    name: "יום A — דחיפה",
    emoji: "💪",
    color: "#e74c3c",
    description: "חזה, כתפיים, טריצפס",
    exercises: [
      {
        id: "pushup",
        name: "שכיבות סמיכה",
        defaultLevel: 1,
        rest: 60,
        tips: "גוף ישר כמו קרש, מרפקים 45° מהגוף",
        muscles: "חזה, טריצפס, כתפיים",
        videoSearch: "push up proper form tutorial calisthenics",
        levels: [
          { label: "על ברכיים",        sets: 3, reps: "8"           },
          { label: "רגיל",              sets: 4, reps: "12"          },
          { label: "רגיל — נפח",        sets: 4, reps: "15"          },
          { label: "טמפו 4-2-1",        sets: 3, reps: "10"          },
          { label: "Archer Push-up",    sets: 3, reps: "6 כל צד"    },
          { label: "חד-יד שלילי",       sets: 3, reps: "4 כל צד"    },
        ],
        steps: [
          "הנח ידיים ברוחב כתפיים, אצבעות מופנות קדימה",
          "גוף ישר לחלוטין מהראש עד לעקבים — שמור על זה לאורך כל התרגיל",
          "הורד את הגוף עד שחזה כמעט נוגע ברצפה",
          "מרפקים ב-45° מהגוף — לא פרושים לצדדים",
          "דחוף חזק למעלה עד לנעילת ידיים מלאה",
          "נשום פנימה בירידה, נשום החוצה בדחיפה",
        ],
        commonMistakes: [
          "ישבן גבוה מדי או שוקע למטה",
          "מרפקים פרושים ל-90° — פוגע בכתפיים",
          "טווח תנועה חלקי בלבד",
        ],
      },
      {
        id: "wide-pushup",
        name: "שכיבות סמיכה רחבות",
        defaultLevel: 1,
        rest: 60,
        tips: "ידיים רחבות מהכתפיים — מדגישות את החזה",
        muscles: "חזה חיצוני",
        videoSearch: "wide push up chest workout form",
        levels: [
          { label: "על ברכיים — רחבות", sets: 3, reps: "8"  },
          { label: "רחבות",             sets: 3, reps: "10" },
          { label: "רחבות — נפח",       sets: 4, reps: "15" },
          { label: "טמפו 4-2-1",        sets: 3, reps: "10" },
          { label: "Typewriter",         sets: 3, reps: "6 כל צד" },
        ],
        steps: [
          "הנח ידיים רחוק מהכתפיים — כ-20 ס\"מ מעבר לרוחב הכתף",
          "אצבעות מופנות מעט החוצה",
          "גוף ישר כמו פלאנק לאורך כל התנועה",
          "הורד עד שחזה נוגע ברצפה — טווח מלא",
          "לחץ חזק החוצה ולמעלה בחזרה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "לא מוריד מספיק נמוך",
          "גוף לא ישר — ישבן מורם",
        ],
      },
      {
        id: "pike-pushup",
        name: "Pike Push-ups",
        defaultLevel: 1,
        rest: 75,
        tips: "ירכיים למעלה, ראש לכיוון הרצפה — כמו הכנה ל-Handstand",
        muscles: "כתפיים, טריצפס",
        videoSearch: "pike push up shoulder workout tutorial",
        levels: [
          { label: "ידיים מוגבהות",          sets: 3, reps: "6" },
          { label: "רגיל",                    sets: 3, reps: "8" },
          { label: "רגיל — נפח",              sets: 3, reps: "12" },
          { label: "Decline Pike",            sets: 3, reps: "8" },
          { label: "HSPU שלילי לקיר",         sets: 3, reps: "5" },
        ],
        steps: [
          "התחל בעמדת Push-up רגילה",
          "הרם ירכיים גבוה עד שגוף יוצר צורת V הפוכה",
          "ידיים ברוחב כתפיים, אצבעות קדימה",
          "הורד ראש לכיוון הרצפה בין הידיים",
          "ראש כמעט נוגע ברצפה — עצור",
          "דחוף חזק למעלה, החזר ירכיים לגובה ה-V",
        ],
        commonMistakes: [
          "ירכיים נמוכות מדי — הופך לפוש-אפ רגיל",
          "ראש לא יורד מספיק בין הידיים",
        ],
      },
      {
        id: "dips",
        name: "Dips על כיסא",
        defaultLevel: 1,
        rest: 75,
        tips: "גב צמוד לכיסא, מרפקים אחורה — לא הצידה",
        muscles: "טריצפס, חזה תחתון",
        videoSearch: "tricep dips chair home workout tutorial",
        levels: [
          { label: "ברכיים כפופות",   sets: 3, reps: "8"  },
          { label: "רגליים ישרות",    sets: 3, reps: "10" },
          { label: "רגליים ישרות — נפח", sets: 4, reps: "12" },
          { label: "טמפו 3-1-1",      sets: 3, reps: "8"  },
          { label: "תרמיל על הגב",    sets: 3, reps: "8"  },
        ],
        steps: [
          "שב על קצה כיסא יציב, ידיים אוחזות בקצה הכיסא לצד הירכיים",
          "הזז ישבן קדימה מהכיסא, רגליים ישרות או כפופות",
          "גב קרוב לכיסא לאורך כל התנועה",
          "הורד גוף כלפי מטה — מרפקים כלפי אחורה, לא הצידה",
          "רד עד שמרפקים ב-90° לפחות",
          "דחוף חזק למעלה דרך הידיים לעמדת ההתחלה",
        ],
        commonMistakes: [
          "מרפקים פרושים הצידה — עומס על כתפיים",
          "גוף רחוק מדי מהכיסא",
          "טווח תנועה קטן מדי",
        ],
      },
      {
        id: "diamond-pushup",
        name: "שכיבות יהלום",
        defaultLevel: 1,
        rest: 60,
        tips: "ידיים בצורת יהלום מתחת לחזה",
        muscles: "טריצפס, חזה פנימי",
        videoSearch: "diamond push up triceps tutorial form",
        levels: [
          { label: "על ברכיים",      sets: 3, reps: "6"  },
          { label: "רגיל",            sets: 3, reps: "8"  },
          { label: "רגיל — נפח",     sets: 3, reps: "12" },
          { label: "Close-grip Decline", sets: 3, reps: "10" },
          { label: "יד אחת מסייעת",  sets: 3, reps: "5 כל צד" },
        ],
        steps: [
          "הנח ידיים מתחת לחזה — אגודלות ואצבעות מורות יוצרות צורת יהלום",
          "גוף ישר, ידיים ממורכזות מתחת לגוף",
          "הורד חזה לכיוון הידיים — מרפקים נשארים קרובים לגוף",
          "ודא שחזה כמעט נוגע ביהלום שיצרת",
          "דחוף חזק למעלה עד לנעילה מלאה",
        ],
        commonMistakes: [
          "מרפקים פרושים הצידה",
          "ידיים לא ממורכזות — נטיה לצד אחד",
        ],
      },
    ],
  },

  {
    id: "pull",
    name: "יום B — משיכה",
    emoji: "🏋️",
    color: "#2980b9",
    description: "גב, ביצפס, כתפיים אחוריות",
    exercises: [
      {
        id: "rows",
        name: "Rows מתחת לשולחן",
        defaultLevel: 1,
        rest: 75,
        tips: "שכב מתחת לשולחן יציב, משוך חזה אל הקצה",
        muscles: "גב רחב, ביצפס",
        videoSearch: "australian pull up table row tutorial bodyweight",
        levels: [
          { label: "ברכיים כפופות",    sets: 3, reps: "8"        },
          { label: "רגליים ישרות",     sets: 4, reps: "10"       },
          { label: "רגליים ישרות — נפח", sets: 4, reps: "12"    },
          { label: "רגליים מורמות",   sets: 3, reps: "10"       },
          { label: "Archer Row",       sets: 3, reps: "6 כל צד" },
        ],
        steps: [
          "שכב על הגב מתחת לשולחן יציב — אחוז בקצה השולחן",
          "ידיים ברוחב כתפיים, גוף ישר מהראש לעקבים",
          "רגליים ישרות, עקבים על הרצפה",
          "משוך חזה אל קצה השולחן — שאף פנימה בעלייה",
          "סחט שכמות ביחד בנקודה הגבוהה ביותר",
          "הורד לאט חזרה לעמדת ההתחלה — נשום החוצה",
        ],
        commonMistakes: [
          "ירכיים שוקעות — גוף לא ישר",
          "לא מגיע עם חזה עד השולחן",
          "ירידה מהירה מדי — אל תוותר על הירידה האקסצנטרית",
        ],
      },
      {
        id: "pullup-negative",
        name: "Pull-up שלילי",
        defaultLevel: 1,
        rest: 90,
        tips: "עלה בקפיצה, רד לאט תוך 5 שניות — בונה כוח pull-up",
        muscles: "גב רחב, ביצפס",
        videoSearch: "negative pull up tutorial beginner how to",
        levels: [
          { label: "Negative 3 שניות",  sets: 3, reps: "4" },
          { label: "Negative 5 שניות",  sets: 3, reps: "5" },
          { label: "Negative 7 שניות",  sets: 3, reps: "5" },
          { label: "Pull-up",            sets: 3, reps: "3" },
          { label: "Pull-up — נפח",      sets: 3, reps: "6" },
          { label: "Pull-up — נפח גבוה", sets: 4, reps: "8" },
        ],
        steps: [
          "קפוץ לאחיזה בבר — סנטר מעל הבר, אחיזה רחבה",
          "החזק עצמך בנקודה הגבוהה של ה-Pull-up",
          "הורד את עצמך לאט ובשליטה — ספור 5 שניות",
          "גוף ישר, אל תניף רגליים",
          "כאשר ידיים ישרות לחלוטין — שחרר ונסה שוב",
          "התמקד בהרגשת הגב בכל הירידה",
        ],
        commonMistakes: [
          "ירידה מהירה מדי — אין תועלת מהיר",
          "הנפת גוף ותנופה במקום שליטה",
        ],
      },
      {
        id: "chinup",
        name: "Chin-ups",
        defaultLevel: 1,
        rest: 90,
        tips: "אחיזה כפות מופנות אליך — קל יותר מ-pull-up",
        muscles: "ביצפס, גב",
        videoSearch: "chin up tutorial proper form beginners",
        levels: [
          { label: "קפיצה + Negative",  sets: 3, reps: "4"  },
          { label: "מקסימום",            sets: 3, reps: "max" },
          { label: "3×5",                sets: 3, reps: "5"  },
          { label: "3×8",                sets: 3, reps: "8"  },
          { label: "4×10",               sets: 4, reps: "10" },
          { label: "L-sit Chin-up",      sets: 3, reps: "5"  },
        ],
        steps: [
          "אחוז בבר כאשר כפות הידיים מופנות אליך — ידיים ברוחב כתפיים",
          "תלה עם ידיים ישרות לחלוטין — שכמות קצת לאחור",
          "משוך עצמך למעלה — מרפקים לצד הגוף ולמטה",
          "עלה עד שסנטר מעל הבר",
          "הורד לאט ובשליטה עד לתלייה מלאה",
          "אל תניף — תנועה נקייה ואיטית",
        ],
        commonMistakes: [
          "לא מגיע לתלייה מלאה בתחתית",
          "הנפת גוף לצבור תנופה",
          "מרפקים פרושים הצידה",
        ],
      },
      {
        id: "superman",
        name: "Superman Hold",
        defaultLevel: 1,
        rest: 45,
        tips: "שכב על הבטן, הרם ידיים ורגליים בו זמנית",
        muscles: "גב תחתון, ישבן",
        videoSearch: "superman hold back extension tutorial",
        levels: [
          { label: "15 שניות",            sets: 3, reps: "15 שניות" },
          { label: "20 שניות",            sets: 3, reps: "20 שניות" },
          { label: "30 שניות",            sets: 3, reps: "30 שניות" },
          { label: "חלופת ידיים-רגליים",  sets: 3, reps: "20 שניות" },
        ],
        steps: [
          "שכב על הבטן, ידיים מושטות קדימה, רגליים ישרות",
          "הרם ידיים, חזה ורגליים בו-זמנית מהרצפה",
          "סחט ישבן וגב תחתון בנקודה הגבוהה",
          "ראש בקו ישר עם עמוד השדרה — אל תרים ראש גבוה",
          "החזק את העמדה לאורך הזמן הנדרש",
          "הורד בשליטה לרצפה",
        ],
        commonMistakes: [
          "הרמת ראש גבוה — לחץ על צוואר",
          "הרמת רק ידיים או רק רגליים",
        ],
      },
      {
        id: "face-pull",
        name: "Face Pull עם גומייה",
        defaultLevel: 1,
        rest: 45,
        tips: "קשור גומייה בגובה הפנים, משוך אל הפנים",
        muscles: "כתפיים אחוריות, גב עליון",
        videoSearch: "face pull resistance band tutorial rotator cuff",
        levels: [
          { label: "גומייה קלה",        sets: 3, reps: "10" },
          { label: "רגיל",              sets: 3, reps: "12" },
          { label: "נפח",               sets: 3, reps: "15" },
          { label: "גומייה + Rotation", sets: 3, reps: "12" },
        ],
        steps: [
          "קשור גומייה לגובה הפנים — לדלת, עמוד או בר",
          "אחוז בשני קצות הגומייה, ידיים בגובה הפנים",
          "עמוד רחוק מספיק שהגומייה מתוחה",
          "משוך את הגומייה ישירות לכיוון הפנים — מרפקים גבוהים",
          "בנקודה הסופית — מרפקים מאחורי הראש, אגרופים ליד האוזניים",
          "הורד לאט בשליטה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "מרפקים נופלים למטה במהלך המשיכה",
          "תנועה מהירה מדי ללא שליטה",
        ],
      },
    ],
  },

  {
    id: "legs-core",
    name: "יום C — רגליים + ליבה",
    emoji: "🦵",
    color: "#27ae60",
    description: "רגליים, ישבן, בטן",
    exercises: [
      {
        id: "squat",
        name: "סקוואט",
        defaultLevel: 1,
        rest: 60,
        tips: "ברכיים מעל אצבעות הרגל, גב ישר, ירד עד 90°",
        muscles: "ארבע ראשי, ישבן",
        videoSearch: "bodyweight squat proper form tutorial",
        levels: [
          { label: "Box Squat",          sets: 3, reps: "12"        },
          { label: "רגיל",               sets: 4, reps: "15"        },
          { label: "נפח",                sets: 4, reps: "20"        },
          { label: "Jump Squat",         sets: 3, reps: "12"        },
          { label: "Pistol — שלילי",     sets: 3, reps: "5 כל רגל" },
          { label: "Pistol Squat",       sets: 3, reps: "5 כל רגל" },
        ],
        steps: [
          "עמוד ברוחב כתפיים, אצבעות הרגל מופנות מעט החוצה",
          "ידיים ישרות קדימה לאיזון, או מקופלות על החזה",
          "שמור גב ישר ולחץ חזה החוצה לאורך כל התנועה",
          "הורד עצמך כאילו אתה יושב על כיסא — ישבן לאחור ולמטה",
          "ירד עד שירכיים מקבילות לרצפה (90°) לפחות",
          "ברכיים נשארות מעל אצבעות הרגל — לא נכנסות פנימה",
          "דחוף דרך העקבים לחזרה לעמדת ההתחלה",
        ],
        commonMistakes: [
          "ברכיים נכנסות פנימה — פוגע בברכיים",
          "עקבים מתרוממים מהרצפה",
          "גב מתעגל — לחץ חזה קדימה",
        ],
      },
      {
        id: "lunge",
        name: "לאנג'ים לאחור",
        defaultLevel: 1,
        rest: 60,
        tips: "צעד גדול לאחור, ברך אחורית כמעט נוגעת ברצפה",
        muscles: "ארבע ראשי, ישבן, ירכיים",
        videoSearch: "reverse lunge proper form tutorial bodyweight",
        levels: [
          { label: "Static Lunge",        sets: 3, reps: "8 כל רגל"  },
          { label: "Reverse Lunge",       sets: 3, reps: "10 כל רגל" },
          { label: "Reverse Lunge — נפח", sets: 3, reps: "15 כל רגל" },
          { label: "Bulgarian Split",     sets: 3, reps: "8 כל רגל"  },
          { label: "Bulgarian — נפח",     sets: 3, reps: "12 כל רגל" },
        ],
        steps: [
          "עמוד זקוף עם ידיים על הירכיים",
          "צעד צעד גדול לאחור עם רגל אחת",
          "הורד ברך אחורית לכיוון הרצפה — כמעט נוגעת",
          "ברך קדמית מעל עקב — לא חורגת מעבר לאצבע הרגל",
          "גב ישר לאורך כל התנועה",
          "דחוף דרך הרגל הקדמית לחזרה לעמדה",
        ],
        commonMistakes: [
          "ברך קדמית חורגת מעבר לאצבע הרגל",
          "פלג גוף עליון נוטה קדימה",
          "צעד קצר מדי — ברך לא יורדת מספיק",
        ],
      },
      {
        id: "glute-bridge",
        name: "Glute Bridge",
        defaultLevel: 1,
        rest: 45,
        tips: "שכב, כפות רגליים קרוב לישבן, הרם ורד לאט",
        muscles: "ישבן, ירכיים אחוריות",
        videoSearch: "glute bridge tutorial proper form hip thrust",
        levels: [
          { label: "שתי רגליים",          sets: 3, reps: "12"        },
          { label: "שתי רגליים — נפח",    sets: 3, reps: "15"        },
          { label: "נפח גבוה",             sets: 3, reps: "20"        },
          { label: "Single Leg",           sets: 3, reps: "10 כל רגל" },
          { label: "Elevated Single Leg",  sets: 3, reps: "10 כל רגל" },
        ],
        steps: [
          "שכב על הגב, ברכיים כפופות, כפות רגליים שטוחות על הרצפה",
          "כפות הרגל קרוב לישבן — כ-30 ס\"מ",
          "ידיים לצד הגוף, כפות ידיים מטה",
          "דחוף דרך העקבים — הרם ישבן למעלה",
          "בנקודה הגבוהה: גוף ישר מכתפיים לברכיים, סחט ישבן חזק",
          "החזק שניה, ואז הורד לאט לרצפה",
        ],
        commonMistakes: [
          "לא סוחט ישבן בחלק העליון",
          "עקבים מתרוממים מהרצפה",
          "ירד מהר מדי — לנצל את הירידה האקסצנטרית",
        ],
      },
      {
        id: "plank",
        name: "פלאנק",
        defaultLevel: 1,
        rest: 45,
        tips: "גוף ישר, ישבן לא למעלה ולא למטה, נשום!",
        muscles: "ליבה, כתפיים",
        videoSearch: "plank proper form tutorial core workout",
        levels: [
          { label: "20 שניות",           sets: 3, reps: "20 שניות" },
          { label: "40 שניות",           sets: 3, reps: "40 שניות" },
          { label: "60 שניות",           sets: 3, reps: "60 שניות" },
          { label: "Side Plank",         sets: 3, reps: "30s כל צד" },
          { label: "Plank + Shoulder Tap", sets: 3, reps: "20 טפיחות" },
        ],
        steps: [
          "שכב על הבטן, עלה למרפקים — מרפקים ישר מתחת לכתפיים",
          "גוף ישר מהראש לעקבים — דמיין קרש",
          "ישבן לא גבוה ולא נמוך — בדיוק בקו הגוף",
          "לחץ אגרופים לרצפה ולחץ ישבן קלות",
          "ראש בקו ישר עם עמוד השדרה — אל תרים ואל תרכין",
          "נשום נורמלית לאורך כל ההחזקה",
        ],
        commonMistakes: [
          "ישבן גבוה מדי — הופך לפוזיציית V",
          "ישבן שוקע למטה — לחץ על גב תחתון",
          "לעצור נשימה — גורם לסחרחורת",
        ],
      },
      {
        id: "mountain-climber",
        name: "Mountain Climbers",
        defaultLevel: 1,
        rest: 45,
        tips: "קצב מהיר, גוף ישר כמו פלאנק",
        muscles: "ליבה, לב-ריאה",
        videoSearch: "mountain climbers proper form cardio core tutorial",
        levels: [
          { label: "איטי",              sets: 3, reps: "10 כל רגל" },
          { label: "רגיל",              sets: 3, reps: "20 כל רגל" },
          { label: "נפח",               sets: 3, reps: "30 כל רגל" },
          { label: "Cross-body",        sets: 3, reps: "20 כל רגל" },
        ],
        steps: [
          "התחל בעמדת Push-up מורחבת — ידיים ישר מתחת לכתפיים",
          "גוף ישר כמו פלאנק — שמור על זה לכל האימון",
          "משוך ברך ימין לכיוון החזה",
          "בזריזות החלף — שלח ימין אחורה ומשוך שמאל קדימה",
          "המשך בקצב מהיר — כמו ריצה במקום",
          "נשום קצבית ואל תעצור נשימה",
        ],
        commonMistakes: [
          "ישבן מורם למעלה — שובר את קו הגוף",
          "ידיים לא ישר מתחת לכתפיים",
          "תנועה איטית מדי — מאבד אפקט קרדיו",
        ],
      },
      {
        id: "hollow-body",
        name: "Hollow Body Hold",
        defaultLevel: 1,
        rest: 45,
        tips: "גב שטוח לרצפה, ידיים ורגליים מורמים, גב תחתון לוחץ לרצפה",
        muscles: "ליבה עמוקה",
        videoSearch: "hollow body hold tutorial gymnastics core",
        levels: [
          { label: "ברכיים כפופות",    sets: 3, reps: "15 שניות" },
          { label: "רגיל",              sets: 3, reps: "20 שניות" },
          { label: "נפח",               sets: 3, reps: "35 שניות" },
          { label: "Hollow Body Rocks", sets: 3, reps: "15"        },
        ],
        steps: [
          "שכב על הגב עם ידיים לצד הגוף",
          "הדחק גב תחתון לרצפה — זה הכי חשוב!",
          "הרם כתפיים ורגליים מהרצפה בו-זמנית",
          "ידיים מושטות מאחורי הראש, רגליים ישרות",
          "גב תחתון תמיד בלחיצה לרצפה — לא ירים",
          "לגרסה קלה יותר: כופף ברכיים לזווית 90°",
          "החזק את העמדה — נשום!",
        ],
        commonMistakes: [
          "גב תחתון מתרומם מהרצפה — מאבד הפעלת ליבה",
          "לא שומר מתח גוף — גוף שקוע",
        ],
      },
    ],
  },
];

/* =====================================================
   WARMUPS — מותאמים לכל יום אימון
   כל תרגיל: { name, duration (שניות), instruction, videoSearch }
   ===================================================== */
const WARMUPS = {
  push: {
    title: "חימום — יום דחיפה",
    duration: 5,
    exercises: [
      { name: "קפיצות ג'ק", duration: 40, instruction: "קפוץ, פרוש ידיים ורגליים, חזור למרכז — קצב בינוני", videoSearch: "jumping jacks warm up" },
      { name: "סיבובי כתפיים", duration: 30, instruction: "ידיים לצדדים, סובב כתפיים קדימה ואחורה — 15 לכל כיוון", videoSearch: "arm circles shoulder warmup" },
      { name: "סיבובי מרפקים", duration: 30, instruction: "כופף מרפקים, סובב בעיגולים גדולים — משחרר מפרקים", videoSearch: "elbow circles warmup" },
      { name: "שכיבות סמיכה על ברכיים", duration: 40, instruction: "5–8 חזרות איטיות, מתמקד בטכניקה — לא בכוח", videoSearch: "knee push up warm up" },
      { name: "Scapular Push-ups", duration: 30, instruction: "ידיים ישרות, הזז שכמות קדימה ואחורה בלי לכופף מרפקים", videoSearch: "scapular push up warmup" },
      { name: "מתיחת חזה בדלת", duration: 30, instruction: "שים יד על מסגרת דלת, סובב גוף החוצה — תרגיש מתיחה בחזה", videoSearch: "doorway chest stretch warmup" },
    ],
  },
  pull: {
    title: "חימום — יום משיכה",
    duration: 5,
    exercises: [
      { name: "קפיצות ג'ק", duration: 40, instruction: "קצב בינוני, 30–40 שניות — מעלה דופק ומחמם כל הגוף", videoSearch: "jumping jacks warm up" },
      { name: "Dead Hang", duration: 30, instruction: "תלה על הבר עם ידיים ישרות — משחרר עמוד שדרה וכתפיים", videoSearch: "dead hang warm up" },
      { name: "סיבובי כתפיים אחוריים", duration: 30, instruction: "ידיים לצדדים, סיבובים גדולים לאחור — 15 חזרות", videoSearch: "shoulder rolls warmup" },
      { name: "Cat-Cow", duration: 40, instruction: "על ארבע, עגל גב למעלה ואז שקע למטה — 10 חזרות איטיות", videoSearch: "cat cow warmup spine" },
      { name: "Band Pull-Apart (או ידיים)", duration: 30, instruction: "ידיים קדימה ברוחב כתפיים, פרוש לצדדים — סחוט שכמות", videoSearch: "band pull apart warmup" },
      { name: "Scapular Rows", duration: 30, instruction: "תלה על בר, הזז שכמות למטה ולאחור בלי לכופף מרפקים", videoSearch: "scapular retraction warmup" },
    ],
  },
  "legs-core": {
    title: "חימום — יום רגליים + ליבה",
    duration: 5,
    exercises: [
      { name: "ריצה במקום", duration: 40, instruction: "הרם ברכיים גבוה — לפחות לגובה הירך, קצב מהיר", videoSearch: "high knees warmup" },
      { name: "סקוואט עם משקל גוף — איטי", duration: 40, instruction: "5 שניות ירידה, 2 שניות למטה, 3 שניות עלייה — 5 חזרות", videoSearch: "slow bodyweight squat warmup" },
      { name: "Hip Circles", duration: 30, instruction: "ידיים על הירכיים, סובב ירכיים בעיגולים גדולים — 10 לכל כיוון", videoSearch: "hip circles warmup mobility" },
      { name: "Leg Swings קדימה-אחורה", duration: 30, instruction: "אחוז בקיר, הניף רגל קדימה ואחורה — 15 לכל רגל", videoSearch: "leg swings front back warmup" },
      { name: "Leg Swings לצדדים", duration: 30, instruction: "אחוז בקיר, הניף רגל לצדדים — 15 לכל רגל", videoSearch: "lateral leg swings warmup" },
      { name: "Glute Bridge איטי", duration: 40, instruction: "3 שניות עלייה, 2 שניות למעלה, 3 שניות ירידה — 5 חזרות", videoSearch: "slow glute bridge warmup" },
    ],
  },
};

/* =====================================================
   CHALLENGE — 50-day calisthenics path
   ===================================================== */
const CHALLENGE_DAYS = [
  // ── שבוע 1: כוח בסיסי ──────────────────────────
  { day: 1,  week: 1, name: "מתח באחיזה רחבה",             muscles: "גב",                   sets: 3, reps: "מקסימום", rest: 90,  emoji: "🏋️", videoSearch: "wide grip pull up" },
  { day: 2,  week: 1, name: "מקבילים — Dips",              muscles: "חזה, טריצפס",           sets: 3, reps: 10,        rest: 90,  emoji: "💪", videoSearch: "parallel bar dips" },
  { day: 3,  week: 1, name: "סקוואט עמוק",                 muscles: "רגליים",                sets: 4, reps: 15,        rest: 60,  emoji: "🦵", videoSearch: "deep squat calisthenics" },
  { day: 4,  week: 1, name: "שכיבות סמיכה יהלום",          muscles: "טריצפס, חזה פנימי",     sets: 3, reps: 12,        rest: 75,  emoji: "💎", videoSearch: "diamond push up" },
  { day: 5,  week: 1, name: "הרמת ברכיים לחזה בתלייה",    muscles: "בטן",                   sets: 3, reps: 15,        rest: 60,  emoji: "🔥", videoSearch: "hanging knee raise" },
  { day: 6,  week: 1, name: "לאנג'ים בהליכה",             muscles: "רגליים, ישבן",          sets: 3, reps: "12 לכל רגל", rest: 60, emoji: "🚶", videoSearch: "walking lunges" },
  { day: 7,  week: 1, name: "Dead Hang — אחיזה סטטית",    muscles: "אמות, אחיזה",           sets: 3, reps: "מקסימום זמן", rest: 90, emoji: "⏱️", videoSearch: "dead hang bar" },
  // ── שבוע 2: טבעות ──────────────────────────────
  { day: 8,  week: 2, name: "שכיבות סמיכה על טבעות",      muscles: "חזה, כתפיים",           sets: 3, reps: 10,        rest: 90,  emoji: "🤸", videoSearch: "ring push up" },
  { day: 9,  week: 2, name: "חתירה בטבעות",               muscles: "גב עליון",              sets: 3, reps: 12,        rest: 75,  emoji: "🏊", videoSearch: "ring row" },
  { day: 10, week: 2, name: "סקוואט בולגרי בטבעות",       muscles: "רגליים",                sets: 3, reps: "10 לכל רגל", rest: 75, emoji: "🦵", videoSearch: "bulgarian split squat rings" },
  { day: 11, week: 2, name: "פלאנק על הטבעות",            muscles: "ליבה",                  sets: 3, reps: "30 שניות", rest: 60,  emoji: "⚡", videoSearch: "ring plank" },
  { day: 12, week: 2, name: "כפיפות המסטרינג בטבעות",     muscles: "ירך אחורית",            sets: 3, reps: 10,        rest: 75,  emoji: "🦵", videoSearch: "ring hamstring curl" },
  { day: 13, week: 2, name: "פשיטות מרפקים בטבעות",       muscles: "טריצפס",                sets: 3, reps: 12,        rest: 75,  emoji: "💪", videoSearch: "ring tricep extension" },
  { day: 14, week: 2, name: "כפיפות ידיים בטבעות",        muscles: "ביצפס",                 sets: 3, reps: 12,        rest: 75,  emoji: "💪", videoSearch: "ring bicep curl" },
  // ── שבוע 3: כוח מתפרץ ──────────────────────────
  { day: 15, week: 3, name: "טיפוס על חבל",               muscles: "גב, אמות",              sets: 3, reps: "עד הקצה", rest: 120, emoji: "🧗", videoSearch: "rope climb calisthenics" },
  { day: 16, week: 3, name: "Monkey Bars — מעבר אופקי",   muscles: "גב, אמות",              sets: 3, reps: "מצד לצד", rest: 90,  emoji: "🐒", videoSearch: "monkey bars traversal" },
  { day: 17, week: 3, name: "Chin-ups — אחיזה צרה הפוכה", muscles: "ביצפס, גב",             sets: 3, reps: "מקסימום", rest: 90,  emoji: "🏋️", videoSearch: "chin up underhand grip" },
  { day: 18, week: 3, name: "שכיבות סמיכה מתפרצות",       muscles: "חזה, כתפיים",           sets: 4, reps: 10,        rest: 75,  emoji: "💥", videoSearch: "explosive push up" },
  { day: 19, week: 3, name: "Jump Squats",                 muscles: "רגליים, כוח מתפרץ",     sets: 4, reps: 12,        rest: 60,  emoji: "🚀", videoSearch: "jump squat" },
  { day: 20, week: 3, name: "טיפוס חבל שלילי",            muscles: "גב, אמות",              sets: 3, reps: "3 ירידות", rest: 120, emoji: "🧗", videoSearch: "rope climb negative" },
  { day: 21, week: 3, name: "L-Sit סטטי על מקבילים",      muscles: "בטן, ירך קדמית",        sets: 3, reps: "מקסימום זמן", rest: 90, emoji: "✋", videoSearch: "L-sit parallel bars" },
  // ── שבוע 4: כבלים ──────────────────────────────
  { day: 22, week: 4, name: "לחיצת חזה בכבלים",           muscles: "חזה",                   sets: 3, reps: 15,        rest: 60,  emoji: "🔗", videoSearch: "cable chest press" },
  { day: 23, week: 4, name: "Rear Delt Fly בכבלים",       muscles: "כתפיים אחוריות",        sets: 3, reps: 15,        rest: 60,  emoji: "🦅", videoSearch: "cable rear delt fly" },
  { day: 24, week: 4, name: "חתירה ביד אחת בכבלים",       muscles: "גב, ליבה",              sets: 3, reps: "12 לכל יד", rest: 60, emoji: "💪", videoSearch: "single arm cable row" },
  { day: 25, week: 4, name: "Woodchopper בכבלים",         muscles: "בטן אלכסונית",          sets: 3, reps: "12 לכל צד", rest: 60, emoji: "🪓", videoSearch: "cable woodchopper" },
  { day: 26, week: 4, name: "Pistol Squat בתמיכת כבלים",  muscles: "רגליים, שיווי משקל",    sets: 3, reps: "8 לכל רגל", rest: 75, emoji: "🎯", videoSearch: "pistol squat cable assist" },
  { day: 27, week: 4, name: "Y-Raise בכבלים",             muscles: "כתפיים, גב עליון",      sets: 3, reps: 15,        rest: 60,  emoji: "🅈",  videoSearch: "cable Y raise" },
  { day: 28, week: 4, name: "מתיחת יד אחורית בכבלים",     muscles: "טריצפס",                sets: 3, reps: "12 לכל יד", rest: 60, emoji: "💪", videoSearch: "cable overhead tricep extension" },
  // ── שבוע 5: ספסל ומשענות ───────────────────────
  { day: 29, week: 5, name: "הרמת רגליים ישרות במשענת",   muscles: "בטן תחתונה",            sets: 3, reps: 15,        rest: 60,  emoji: "🔥", videoSearch: "captain chair leg raise straight" },
  { day: 30, week: 5, name: "Sit-ups בשיפוע שלילי",       muscles: "בטן",                   sets: 3, reps: 15,        rest: 60,  emoji: "💪", videoSearch: "decline sit up" },
  { day: 31, week: 5, name: "שכיבות סמיכה בשיפוע שלילי",  muscles: "חזה עליון, כתפיים",     sets: 3, reps: 12,        rest: 75,  emoji: "📐", videoSearch: "decline push up" },
  { day: 32, week: 5, name: "Step-ups על הספסל",          muscles: "רגליים, ישבן",          sets: 3, reps: "12 לכל רגל", rest: 60, emoji: "🪜", videoSearch: "bench step up" },
  { day: 33, week: 5, name: "Bench Dips",                  muscles: "טריצפס, חזה",           sets: 3, reps: 15,        rest: 60,  emoji: "🪑", videoSearch: "bench dips tricep" },
  { day: 34, week: 5, name: "הרמת רגליים הצידה במשענת",   muscles: "אלכסונים",              sets: 3, reps: "15 לכל צד", rest: 60, emoji: "↔️", videoSearch: "captain chair side leg raise" },
  { day: 35, week: 5, name: "שכיבות סמיכה רחבות מקבילים", muscles: "חזה, כתפיים",           sets: 3, reps: 12,        rest: 75,  emoji: "🤲", videoSearch: "wide push up parallel bars" },
  // ── שבוע 6: שיווי משקל ─────────────────────────
  { day: 36, week: 6, name: "שיווי משקל רגל אחת",         muscles: "רגליים, יציבות",        sets: 3, reps: "60 שניות לכל רגל", rest: 45, emoji: "🧘", videoSearch: "single leg balance" },
  { day: 37, week: 6, name: "Lateral Jumps מעל פלטפורמות", muscles: "רגליים, קואורדינציה",  sets: 4, reps: 20,        rest: 60,  emoji: "↔️", videoSearch: "lateral jump platform" },
  { day: 38, week: 6, name: "שכיבות סמיכה על קצות אצבעות", muscles: "אמות, חזה",            sets: 3, reps: 10,        rest: 75,  emoji: "☝️", videoSearch: "fingertip push up" },
  { day: 39, week: 6, name: "לאנג'ים סטטיים על פלטפורמה", muscles: "רגליים, ישבן",          sets: 3, reps: "12 לכל רגל", rest: 60, emoji: "🦵", videoSearch: "elevated lunge" },
  { day: 40, week: 6, name: "דחיפות כוח מתפרצות",         muscles: "חזה, כתפיים",           sets: 4, reps: 10,        rest: 75,  emoji: "💥", videoSearch: "explosive push up wall" },
  { day: 41, week: 6, name: "פלאנק דינמי בין פלטפורמות",  muscles: "ליבה, כתפיים",          sets: 3, reps: "45 שניות", rest: 60,  emoji: "⚡", videoSearch: "dynamic plank" },
  { day: 42, week: 6, name: "מתח אחיזה משתנה",            muscles: "גב, ביצפס",             sets: 3, reps: "מקסימום", rest: 90,  emoji: "🏋️", videoSearch: "mixed grip pull up" },
  // ── שבוע 7: אתגר גמר ───────────────────────────
  { day: 43, week: 7, name: "מתח + ברכיים לחזה",          muscles: "גב, בטן",               sets: 3, reps: 8,         rest: 90,  emoji: "🔥", videoSearch: "pull up knee raise" },
  { day: 44, week: 7, name: "Pike Push-up",                muscles: "כתפיים, טריצפס",        sets: 3, reps: 12,        rest: 75,  emoji: "🔺", videoSearch: "pike push up" },
  { day: 45, week: 7, name: "Nordic Curl",                 muscles: "ירך אחורית",            sets: 3, reps: 6,         rest: 90,  emoji: "🦵", videoSearch: "nordic hamstring curl" },
  { day: 46, week: 7, name: "Tuck Planche Hold",           muscles: "כתפיים, ליבה",          sets: 3, reps: "מקסימום זמן", rest: 90, emoji: "✈️", videoSearch: "tuck planche hold" },
  { day: 47, week: 7, name: "Box Jump",                    muscles: "רגליים, כוח מתפרץ",     sets: 4, reps: 8,         rest: 75,  emoji: "📦", videoSearch: "box jump" },
  { day: 48, week: 7, name: "Archer Push-up",              muscles: "חזה, כתפיים, יד",       sets: 3, reps: "8 לכל צד", rest: 90, emoji: "🏹", videoSearch: "archer push up" },
  { day: 49, week: 7, name: "Muscle-up ניסיון",           muscles: "גב, חזה, טריצפס",       sets: 3, reps: "מקסימום", rest: 120, emoji: "👑", videoSearch: "muscle up tutorial" },
  { day: 50, week: 7, name: "Full Challenge — כל הגוף",   muscles: "כל הגוף",               sets: 1, reps: "מעגל שלם", rest: 60, emoji: "🏆", videoSearch: "calisthenics full body circuit" },
];
